<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3a2b2b05856924a391074e6bb6f82bab
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'RunRace\\Tests\\' => 14,
            'RunRace\\Admin\\' => 14,
            'RunRace\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'RunRace\\Tests\\' => 
        array (
            0 => __DIR__ . '/../..' . '/tests',
        ),
        'RunRace\\Admin\\' => 
        array (
            0 => __DIR__ . '/../..' . '/admin',
        ),
        'RunRace\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'RunRace\\RunRacePlugin' => __DIR__ . '/../..' . '/includes/RunRacePlugin.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3a2b2b05856924a391074e6bb6f82bab::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3a2b2b05856924a391074e6bb6f82bab::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit3a2b2b05856924a391074e6bb6f82bab::$classMap;

        }, null, ClassLoader::class);
    }
}
