<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'RunRace\\Tests\\' => array($baseDir . '/tests'),
    'RunRace\\Admin\\' => array($baseDir . '/admin'),
    'RunRace\\' => array($baseDir . '/includes'),
);
